name: "release docker"

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        arch: [ "x86_64", "aarch64" ]

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          rm -rf ./pkg
          mkdir -p ./pkg

      - name: Docker
        run: |
          curl -o ./pkg/docker.tgz https://download.docker.com/linux/static/stable/${{ matrix.arch }}/docker-27.5.1.tgz

      - name: Compose
        run: |
          curl -o ./pkg/docker-compose https://github.com/docker/compose/releases/download/v2.33.0/docker-compose-linux-${{ matrix.arch }}

      - name: Package
        run: |
          tar cvzf docker-${{ matrix.arch }}.tar.gz pkg *.sh *.md

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          name: v27.5.1
          tag_name: v27.5.1
          make_latest: ${{ startsWith(github.ref_name, 'v') }}
          prerelease: false
          generate_release_notes: true
          append_body: true
          files: |
            *.tar.gz
