name: "release docker"

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  packages: write

jobs:
  download:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        arch: [ "x86_64", "aarch64" ]

    steps:
      - name: Setup
        run: |
          rm -rf ./pkg/${{ matrix.arch }}
          mkdir -p ./pkg/${{ matrix.arch }}

      - name: Download binary
        working-directory: ./pkg/${{ matrix.arch }}
        run: |
          curl -o docker.tgz https://download.docker.com/linux/static/stable/${{ matrix.arch }}/docker-27.5.1.tgz
          curl -o docker-compose https://github.com/docker/compose/releases/download/v2.33.0/docker-compose-linux-${{ matrix.arch }}

  upload:
    needs:
      - download

    steps:
      - name: Tar
        run: |
          tar cvzf docker.tar.gz pkg *.sh *.md

      - name: Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          #token: ${{ secrets.GITHUB_TOKEN }}
          name: docker-${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          make_latest: true
          prerelease: false
          generate_release_notes: true
          append_body: true
          files: |
            *.tar.gz