name: "release docker"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        arch: [ "x86_64", "aarch64" ]

    env:
      version: 27.5.1

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Download
        run: |
          curl -fsSL -o docker.tgz https://download.docker.com/linux/static/stable/${{ matrix.arch }}/docker-${{ env.version }}.tgz
          curl -fsSL -o docker-compose https://github.com/docker/compose/releases/download/v2.33.0/docker-compose-linux-${{ matrix.arch }}

      - name: Package
        run: |
          case ${{ matrix.arch }} in
          aarch64)
            GOARCH="arm64" ;;
          *)
            GOARCH="amd64" ;;
          esac
          
          echo ${GOARCH}
          GOARCH=${GOARCH} go build -o config-doctor main.go
          tar cvzf docker-${{ matrix.arch }}.tar.gz --owner=root --group=root docker* *.md *.sh config*

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.version }}
          tag_name: v${{ env.version }}
          make_latest: true
          prerelease: false
          generate_release_notes: true
          append_body: true
          files: |
            *.tar.gz
